;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC sf.firehose.v2.Fetch Client Implementation
;;;----------------------------------------------------------------------------------
(ns sf.firehose.v2.Fetch.client
  (:require [sf.firehose.v2 :refer :all]
            [com.google.protobuf :as com.google.protobuf]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(def Fetch-service-name "sf.firehose.v2.Fetch")

(defn Block
  ([client params] (Block client {} params))
  ([client metadata params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "sf.firehose.v2.Fetch"
              :method  "Block"
              :input   {:f sf.firehose.v2/new-SingleBlockRequest :ch input}
              :output  {:f sf.firehose.v2/pb->SingleBlockResponse :ch output}
              :metadata metadata}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output)))))))

